/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.io.File;
import javax.swing.JOptionPane;
import java.util.regex.*;
import javax.swing.JFileChooser;
/**
 *
 * @author Jeel
 */
public class ui_frame extends javax.swing.JFrame {

    /**
     * Creates new form ui_frame
     */
    public ui_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ui_mainPanel = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        lbl_fname = new javax.swing.JLabel();
        lbl_lname = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_age = new javax.swing.JLabel();
        lbl_message = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_message = new javax.swing.JTextArea();
        btn_submit = new javax.swing.JButton();
        errortxt_fname = new javax.swing.JLabel();
        errortxt_lname = new javax.swing.JLabel();
        errortxt_age = new javax.swing.JLabel();
        errortxt_email = new javax.swing.JLabel();
        errortxt_message = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_image = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ui_mainPanel.setBackground(new java.awt.Color(204, 255, 204));

        lbl_title.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Customer Registration Form");

        lbl_fname.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lbl_fname.setText("First Name :");

        lbl_lname.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lbl_lname.setText("Last Name :");

        lbl_email.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lbl_email.setText("Email :");

        lbl_age.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lbl_age.setText("Age :");

        lbl_message.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lbl_message.setText("Message : ");

        txt_fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_fnameKeyReleased(evt);
            }
        });

        txt_lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_lnameKeyReleased(evt);
            }
        });

        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_emailKeyReleased(evt);
            }
        });

        txt_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_ageKeyReleased(evt);
            }
        });

        txta_message.setColumns(20);
        txta_message.setRows(5);
        txta_message.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txta_messageKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txta_message);

        btn_submit.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btn_submit.setText("SUBMIT");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        errortxt_fname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        errortxt_fname.setForeground(new java.awt.Color(255, 0, 0));

        errortxt_lname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        errortxt_lname.setForeground(new java.awt.Color(255, 0, 0));

        errortxt_age.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        errortxt_age.setForeground(new java.awt.Color(255, 0, 0));

        errortxt_email.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        errortxt_email.setForeground(new java.awt.Color(255, 0, 0));

        errortxt_message.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        errortxt_message.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel1.setText("Upload Image");

        btn_image.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btn_image.setText("Upload");
        btn_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ui_mainPanelLayout = new javax.swing.GroupLayout(ui_mainPanel);
        ui_mainPanel.setLayout(ui_mainPanelLayout);
        ui_mainPanelLayout.setHorizontalGroup(
            ui_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ui_mainPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(ui_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ui_mainPanelLayout.createSequentialGroup()
                        .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ui_mainPanelLayout.createSequentialGroup()
                        .addGroup(ui_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ui_mainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(192, 192, 192)
                                .addComponent(btn_image))
                            .addGroup(ui_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ui_mainPanelLayout.createSequentialGroup()
                                    .addGroup(ui_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lbl_lname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_fname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(83, 83, 83)
                                    .addGroup(ui_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_lname)
                                        .addComponent(txt_fname)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ui_mainPanelLayout.createSequentialGroup()
                                    .addComponent(lbl_age, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ui_mainPanelLayout.createSequentialGroup()
                                    .addComponent(lbl_email)
                                    .addGap(118, 118, 118)
                                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ui_mainPanelLayout.createSequentialGroup()
                                    .addComponent(lbl_message)
                                    .addGap(94, 94, 94)
                                    .addComponent(jScrollPane1))
                                .addComponent(btn_submit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(ui_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ui_mainPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ui_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(errortxt_age, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(errortxt_lname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(errortxt_fname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(errortxt_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(ui_mainPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(errortxt_message, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        ui_mainPanelLayout.setVerticalGroup(
            ui_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ui_mainPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(ui_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_fname)
                    .addGroup(ui_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errortxt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(ui_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_lname)
                    .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errortxt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(ui_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_age)
                    .addComponent(txt_age)
                    .addComponent(errortxt_age, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(ui_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_email)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errortxt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(ui_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_message)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errortxt_message, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(btn_submit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ui_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_image))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ui_mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ui_mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        String fname = txt_fname.getText();
        String lname = txt_lname.getText();
        String age = txt_age.getText();
        String email = txt_email.getText();
        String message = txta_message.getText();
        //System.out.println(" " + fname +" "+ lname +" "+ age +" "+ email +" "+ message);
        if(fname.equals("")){
        errortxt_fname.setText("Please enter first name, you can't leave the space blank, it is mandatory");
        }
        if(lname.equals("")){
        errortxt_lname.setText("Please enter last name, you can't leave the space blank, it is mandatory");
        }
        if(age.equals("")){
        errortxt_age.setText("Please enter age, you can't leave the space blank, it is mandatory");
        }
        if(email.equals("")){
        errortxt_email.setText("Please enter your email, you can't leave the space blank, it is mandatory");
        }
        if(message.equals("")){
        errortxt_message.setText("Please enter the message, you can't leave the space blank, it is mandatory");
        }
        else{
        JOptionPane.showMessageDialog(this, "The first name and last name of the customer is " + fname +" "+ lname +"\n The age of the customer is "+ age +"\n Email I'd is "+ email +"\n The message sent by the customer is "+ message, "Customer Information validated successfully", HEIGHT);
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void txt_fnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fnameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{2,20}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txt_fname.getText());
        if(!match.matches()){
            errortxt_fname.setText("Please enter Only Alphabets in first name");
        }
        else {
            errortxt_fname.setText(null);
        }
    }//GEN-LAST:event_txt_fnameKeyReleased

    private void txt_lnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lnameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{2,20}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txt_lname.getText());
        if(!match.matches()){
            errortxt_lname.setText("Please enter Only Alphabet in last name");
        }
        else {
            errortxt_lname.setText(null);
        }
    }//GEN-LAST:event_txt_lnameKeyReleased

    private void txt_ageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ageKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,110}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txt_age.getText());
        if(!match.matches()){
            errortxt_age.setText("Please enter only number, no invalid characters allowed");
        }
        else {
            errortxt_age.setText(null);
        }
    }//GEN-LAST:event_txt_ageKeyReleased

    private void txt_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9]{0,30}@[a-zA-Z]{0,10}.[a-zA-Z]{0,3}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txt_email.getText());
        if(!match.matches()){
            errortxt_email.setText("Please enter a valid Email address (for e.g; abc@gmail.com)");
        }
        else {
            errortxt_email.setText(null);
        }
    }//GEN-LAST:event_txt_emailKeyReleased

    private void txta_messageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txta_messageKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9 ]{20,100}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txta_message.getText());
        if(!match.matches()){
            errortxt_message.setText("Please describe your message, write atleast 20 characters");
        }
        else {
            errortxt_message.setText(null);
        }
    }//GEN-LAST:event_txta_messageKeyReleased

    private void btn_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imageActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename=null;
        filename = f.getAbsolutePath();
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(filename);
        int a = JOptionPane.showConfirmDialog(this, "Your Selected Image is Displayed", "Uploaded Image", JOptionPane.OK_OPTION , JOptionPane.PLAIN_MESSAGE, icon);
    }//GEN-LAST:event_btn_imageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ui_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ui_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ui_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ui_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ui_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_image;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel errortxt_age;
    private javax.swing.JLabel errortxt_email;
    private javax.swing.JLabel errortxt_fname;
    private javax.swing.JLabel errortxt_lname;
    private javax.swing.JLabel errortxt_message;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_age;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_fname;
    private javax.swing.JLabel lbl_lname;
    private javax.swing.JLabel lbl_message;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextArea txta_message;
    private javax.swing.JPanel ui_mainPanel;
    // End of variables declaration//GEN-END:variables
}
